stages:
  - name: MyStage
    inputs:
      - type: git
        branch: release
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    jobs:
      - name: Deploy
        type: deployer
        target:
          region_id: 'ibm:yp:us-south'
          organization: PradeepB
          space: dev
          application: ids2otc
        script: |
          #!/bin/bash
          cd com.ibm.devops.otc.migration.entry
          cf push "${CF_APP}"
