stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
        artifact_dir: ''
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
        service: '${SAMPLE_REPO}'
    triggers:
      - type: stage
    jobs:
      - name: Deploy to dev
        type: deployer
        target:
          region_id: 'ibm:ys1:us-south'
          organization: dusisarath@in.ibm.com
          space: dev
          application: GitRepoMoveToStage1
        script: |-
          #!/bin/bash
          cf push "${CF_APP}"

          # View logs
          #cf logs "${CF_APP}" --recent
