stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    properties:
      - name: ljsdhklzsdklfj
        value: |-
          asdklsdfg
          sldkfgkljkl;
          ]sdglkhklsjdl;gjkljsdlkg
        type: text_area
    jobs:
      - name: Build
        type: builder
        artifact_dir: ''
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    properties:
      - name: deploy_prop
        value: asfklkhkljaklsf
        type: text
    jobs:
      - name: Deploy to dev
        type: deployer
        target:
          region_id: '${PROD_REGION_ID}'
          organization: '${PROD_ORG_NAME}'
          space: '${PROD_SPACE_NAME}'
          application: '${CF_APP_NAME}'
        script: |-
          #!/bin/bash
          cf push "${CF_APP}"

          # View logs
          #cf logs "${CF_APP}" --recent
