stages:
  - name: Build and Test Stage
    inputs:
      - type: git
        branch: master
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    properties:
      - name: dsdsd
        value: sdsdsds
        type: text
      - name: sdsdsd
        value: sdsdsdsdsdd
        type: text_area
    jobs:
      - name: Build
        type: builder
        artifact_dir: ''
      - name: MyTest
        type: tester
        script: |-
          #!/bin/bash
          # invoke tests here
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build and Test Stage
        job: Build
        service: '${SAMPLE_REPO}'
    triggers:
      - type: stage
    jobs:
      - name: Deploy to dev
        type: deployer
        target:
          region_id: 'ibm:yp:us-south'
          organization: dusisarath@in.ibm.com
          space: Dev
          application: Microservices-UI-dusisarath-1347
        script: |-
          #!/bin/bash
          cf push "${CF_APP}"

          # View logs
          #cf logs "${CF_APP}" --recent
