stages:
  - name: MyStage
    inputs:
      - type: git
        branch: master
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    jobs:
      - name: Deploy
        type: deployer
        target:
          region_id: '${PROD_REGION_ID}'
          organization: '${PROD_ORG_NAME}'
          space: '${PROD_SPACE_NAME}'
          application: '${CF_APP_NAME}'
        script: |
          #!/bin/bash
          cd com.ibm.devops.otc.migration.entry
          cf push "${CF_APP}"
