stages:
  - name: Build Stage
    properties:
      - name: ljsdhklzsdklfj
        value: |-
          asdklsdfg
          sldkfgkljkl;
          ]sdglkhklsjdl;gjkljsdlkg
        type: text_area
      - name: Sarath
        value: Dusi
        type: text
    jobs:
      - name: Build
        type: builder
        artifact_dir: ''
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
        service: '${SAMPLE_REPO}'
    triggers:
      - type: stage
    properties:
      - name: deploy_prop
        value: asfklkhkljaklsf
        type: text
    jobs:
      - name: Deploy to dev
        type: deployer
        target:
          region_id: 'ibm:yp:us-south'
          organization: dusisarath@in.ibm.com
          space: Dev
          application: Delivery-Pipeline-Testing-App
        script: |-
          #!/bin/bash
          cf push "${CF_APP}"

          # View logs
          #cf logs "${CF_APP}" --recent
