stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
        build_type: ant
        script: |-
          #!/bin/bash
          ant -DARCHIVE_DIR=${ARCHIVE_DIR}
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    jobs:
      - name: Deploy
        type: deployer
        target:
          region_id: '${PROD_REGION_ID}'
          organization: '${PROD_ORG_NAME}'
          space: '${PROD_SPACE_NAME}'
          application: '${CF_APP_NAME}'
        script: 'cf push ${CF_APP}'
