stages:
  - name: MyStage
    inputs:
      - type: git
        branch: release
        service: '${SAMPLE_REPO}'
    triggers:
      - type: commit
    jobs:
      - name: Deploy
        type: deployer
        target:
          region_id: 'ibm:yp:us-south'
          organization: dusisarath@in.ibm.com
          space: Dev
          application: TestProject
        script: |
          #!/bin/bash
          cd com.ibm.devops.otc.migration.entry
          cf push "${CF_APP}"
  - name: 2nd Stage
    triggers:
      - type: stage
    properties:
      - name: sasa
        value: sasass
        type: text
    jobs:
      - name: deploy stage
        type: deployer
        target:
          region_id: 'ibm:yp:us-south'
          organization: dusisarath@in.ibm.com
          space: Dev
          application: TestProject
        script: |
          #!/bin/bash
          cf push "${CF_APP}"
